### ISSUE TITLE
Pull requests are not abled to be made

### ISSUE THREAD

**Issue by QuietOne** [jeppestaerk/alfred-currency-conversion#11]
I have tried to clone the project and to add PR regarding currency RSD, but I am unable to do so, as I can't upstream any branch needed for making PR.

I don't know if it is complicated, but if it is for some reason, than this ticket is just for RSD currency. I have the image for it.
![RSD](https://user-images.githubusercontent.com/6277832/105965159-60720700-6083-11eb-987c-ab1aca8724c7.png)

**Comment by QuietOne** [comment]
@jeppestaerk @wallasehuang @chirul0

**Comment by chirul0** [comment]
@QuietOne Did you create a [fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)?

**Comment by QuietOne** [comment]
Thanks. I made it now.
