### ISSUE TITLE
ERROR: input.scriptfilter

### ISSUE THREAD

**Issue by antonynotna** [jeppestaerk/alfred-currency-conversion#3]
Since yesterday I'm getting this error message:

`[2018-06-20 11:07:29][ERROR: input.scriptfilter] Code 1: {
	"items": [
		{
			"title": "HTTPError: Response code 404 (Not Found)\n    at stream.catch.then.data (/Users/antonynotna/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/alfred-currency-conversion/node_modules/got/index.js:123:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nHTTPError: Response code 404 (Not Found)\n    at stream.catch.then.data (/Users/antonynotna/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/alfred-currency-conversion/node_modules/got/index.js:123:13)\n    at <anonymous>\n```\n\n-\nCurrency Converter 0.1.14\nAlfred 3.6.1\ndarwin x64 17.6.0",
				"largetype": "HTTPError: Response code 404 (Not Found)\n    at stream.catch.then.data (/Users/antonynotna/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/alfred-currency-conversion/node_modules/got/index.js:123:13)\n    at <anonymous>"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}`

**Comment by jeppestaerk** [comment]
Fixed
